### ISSUE TITLE
💡 cache index information

### ISSUE THREAD

**Issue by Fonger** [matteodelabre/mongoose-beautiful-unique-validation#10]
If we can cache the index information in memory,
then we don't need to query indexes every time when an error occurs

better performance

**Comment by matteodelabre** [comment]
Hi, thank you for your interest!
I guess you mean caching the results from this call: `collection.indexInformation();`.
If so, that sounds like a good idea, I will try to make that change this weekend.

**Comment by Fonger** [comment]
@matteodelabre exactly :+1:

**Comment by matteodelabre** [comment]
Fixed by cb4d8ea thank you. :)
