### ISSUE TITLE
💡display model name in error

### ISSUE THREAD

**Issue by Fonger** [matteodelabre/mongoose-beautiful-unique-validation#11]
In regular mongoose error, the default message shoud be `ModelName` validation failed

e.g. 
{
    "name": "ValidationError",
    "message": "**User** Validation failed",
    "errors": {
        "name": {
            "name":"ValidatorError",
            "properties": {
                "type": "Duplicate value",
                "message": "Custom error message",
                "path": "name",
                "value": "John"
            },
            "message": "Custom error message",
            "kind": "Duplicate value",
            "path": "name",
            "value": "John"
        }
    }
}

**Comment by matteodelabre** [comment]
That's a good idea, thank you!
I will try to make that change this weekend.
