### ISSUE TITLE
Error Regex does not match all Mongo Error structures

### ISSUE THREAD

**Issue by galenandrew** [matteodelabre/mongoose-beautiful-unique-validation#13]
_Using Mongo version 3.2.4 installed on Ubuntu 14.04_

It seems as if the `errorRegex` ([index.js#L6](https://github.com/matteodelabre/mongoose-beautiful-unique-validation/blob/master/index.js#L6)) you are using does not match all structures of E11000 duplicate key errors.

For example: https://regex101.com/r/lA2dZ7/1

---

_Error Regex_
```js
var errorRegex = /index:\s*.+?\.\$(\S*)\s*dup key:\s*\{(.*?)\}/;
```

_Matching Error Structure_
```
E11000 duplicate key error index: database-name.users.$username_1 dup key: { : "andrew" }
```

_Non-matching Error Structure_
```
E11000 duplicate key error collection: database-name.users index: username_1 dup key: { : "andrew" }
```

**Comment by matteodelabre** [comment]
Hi there, thank you for your interest. :)
I have to admit that I don't know much about collections in that context.
Could a regex like that one do the job?

```js
/(?:index|collection):\s*.+?\.\$(\S*)\s*dup key:\s*\{(.*?)\}/
```

Or can you see more edge cases?

**Comment by galenandrew** [comment]
@matteodelabre thanks for the quick response!

I don't think that regex will match the second error. Specificly the `\.\$` part of the regex won't match the second example.

For instance, this…
```
index: database-name.users.$username_1
```
vs
```
collection: database-name.users index: username_1
```

/cc @bvyask

**Comment by matteodelabre** [comment]
Do the part after `index:` refer to the index name in the case of collections, just like with a regular index? 
If so, think the following regex should match both cases:

```js
/index:\s*(?:.+?\.\$)?(\S*)\s*dup key:\s*\{(.*?)\}/
```

Do you have any clue why the $ is ommited in the second case?

**Comment by galenandrew** [comment]
Yes, that regex seems to match both cases. No clue why Mongo is omitting the `$` and have not been able to find any documentation about the change.

**Comment by galenandrew** [comment]
@matteodelabre would you like me to submit a PR for this? or will you make the change?

**Comment by matteodelabre** [comment]
I'd greatly appreciate it! Thank you :)

**Comment by galenandrew** [comment]
Will do!

**Comment by Fonger** [comment]
3.2.4
E11000 duplicate key error collection: test.models index: a_1_b.b_1 dup key: { : 1.0, : 1.0 }

3.0.9
E11000 duplicate key error index: GG.qq.$a_1  dup key: { : 1.0 }"

2.6.11
insertDocument :: caused by :: 11000 E11000 duplicate key error index: test.haha.$a_1_b.b_1  dup key: { : 1.0, : 1.0 }"

2.4.14
E11000 duplicate key error index: test.haha.$a_1_b.b_1  dup key: { : 1.0, : 1.0 }"

**Comment by galenandrew** [comment]
The updated regex appears to match all scenarios: https://regex101.com/r/lA2dZ7/2

Correct @Fonger?
