### ISSUE TITLE
Support `Model.create`

### ISSUE THREAD

**Issue by JeffreyChan** [matteodelabre/mongoose-beautiful-unique-validation#16]
I want to mongoose-beautiful-unique-validation  support mongoose.Model.create method, if you have time ,please fix this. thanks a lot.

**Comment by matteodelabre** [comment]
Working on this right now. I think this raises a couple of questions.

* `Model.create` uses `save` internally so it should already work, except it doesn't.
* Should we also support `Model.insertMany`, which doesn't use `save` internally?
* Should we also support `Model.update`?

This could create a lot of duplicate code. Would be great to find a way to shortcut that. I'm going to create a pull request with tests.

**Comment by JeffreyChan** [comment]
I just learn MEAN from this demo: CRUD.NodeJSWithTypescriptAndMongoose.zip
I think his code indicates mongoose Model like a repository. should not call model.save directly. 
I don't know how to say, if call model.save, it will make code ugly. at least is my thought.
I think we can leave Model.update, and do check in our business logic.
I will try Model.create in my project, thanks a lot.

**Comment by JeffreyChan** [comment]
but if support Model.update will be nice. can a switch offer to use update or not. it's very good. Do you think?

**Comment by JeffreyChan** [comment]
still can't work for me. it's kind of odd.

**Comment by raitucarp** [comment]
what is the status of this issue @matteodelabre ?

**Comment by matteodelabre** [comment]
Hi @raitucarp, unfortunately I didn't have enough time to address this issue recently. I will look into it as soon as possible. Until then, pull requests are always welcome. ;)

**Comment by matteodelabre** [comment]
This is now supported in 5.0.0! :tada: 
@JeffreyChan @raitucarp

**Comment by raitucarp** [comment]
ok thanks
