### ISSUE TITLE
Does not support global .plugin method

### ISSUE THREAD

**Issue by mickyginger** [matteodelabre/mongoose-beautiful-unique-validation#25]
It would be great to be able to plug this in to all schemas, by using the mongoose singleton .plugin method as documented here:

http://mongoosejs.com/docs/plugins.html

```javascript
let mongoose = require('mongoose');
let beautifyUnique = require('mongoose-beautiful-unique-validation');

mongoose.plugin(beutifyUnique);
```

**Comment by matteodelabre** [comment]
Cool idea! This would reduce boilerplate on some projects.

Currently, the module reads information about the schema it's plugged onto as soon as it is applied, so it cannot be plugged in before declaring the indexes―as stated in the docs. This is the underlying issue to fix if we want to use it as a global plugin.

This step is only needed to gather the custom duplicate error messages that the users declare on their schemata. Another solution would be to move custom error messages to the plugin's options; however, this would mean a departure from the standard validators' behavior (eg. the [required](http://mongoosejs.com/docs/api.html#schematype_SchemaType-required) validator), and is not applicable to the global plugin.

If we want to keep the error messages customizable inside the indexes declaration, we should either:

* find some way to hook into `mongoose` whenever an index is added;
* hook up just before schemata are compiled to models.

**Comment by matteodelabre** [comment]
So, I can't reproduce your issue after further investigating. If I plug in the module globally on the tests, it works. Could you provide more information about your use case?

**Comment by mickyginger** [comment]
So I'm adding `mongoose.plugin(beautifyUnique)` in the `app.js` file. I've tried adding the plugin to the `mongoose` singleton before and after instantiating my models.

I'll setup a repo shortly and send you a link.

**Comment by mickyginger** [comment]
https://github.com/mickyginger/wdi-ldn-shoes-api

There's a seeds file if you want to run it `node db/seeds`... Works fine if you add the plugin directly to the `userSchema`, but not to `mongoose`.

**Comment by matteodelabre** [comment]
I tried running `node db/seeds` but I get the following error:

```
ReferenceError: User is not defined
    at /home/matteo/Développement/wdi-ldn-shoes-api/db/seeds.js:39:3
```

**Comment by mickyginger** [comment]
Oops... updated. Give it a try now...

**Comment by matteodelabre** [comment]
If I run `node db/seeds`, the error is indeed not beautified. But this is because in the `db/seeds.js` you do not apply the plugin to mongoose. Is it intended?

**Comment by mickyginger** [comment]
Hmm, ok, odd... I couldn't replicate that at first, but then after switching to node v6.2.1 and then back to node v4.4.5, everything is working as expected.

I think perhaps Sublime was caching something??

Anyway, you can close this ticket. Thanks for your assistance.

**Comment by matteodelabre** [comment]
Glad to help! :tada:
