### ISSUE TITLE
No Update hook?

### ISSUE THREAD

**Issue by Bosek** [matteodelabre/mongoose-beautiful-unique-validation#32]
There is missing update hook on last version. Intended? When I try findOneAndUpdate, it works.

```
"mongoose": "^4.6.5",
"mongoose-beautiful-unique-validation": "^5.1.1",
```

**Comment by rodrigogs** [comment]
Use save function to update your model. Update function doesn't provide enough information to build a ValidationError.

**Comment by rodrigogs** [comment]
Just found it: 

https://github.com/blakehaswell/mongoose-unique-validator#find--updates

**Comment by matteodelabre** [comment]
Hi folks! Sorry for the delay in answering your questions. Model.update() should indeed be supported but wasn’t correctly tested so I didn’t notice that it wasn’t working correctly. I’m working on it in #37.

**Comment by matteodelabre** [comment]
This will be fixed in the next major version. Thanks again for the report!
