### ISSUE TITLE
ValidationError contains empty errors property

### ISSUE THREAD

**Issue by martijnhiemstra** [matteodelabre/mongoose-beautiful-unique-validation#43]
I have a User mongoose schema with this property:

    email: {
      type: String,
      required: 'email.blank',
      validate: emailValidator,
      unique: true
    }

When I try and save a user I get a ValidationError however the errors property in ValidationError in empty. I have also tried this:

    email: {
      type: String,
      required: 'email.blank',
      validate: emailValidator,
      unique: 'email.conflict'
    }
 
However still the errors propert in ValidationError is empty. If I remove the unique property then everything works fine.

**Comment by niftylettuce** [comment]
@martijnhiemstra is `emailValidator` getting recognized as async?

> Custom validators can also be asynchronous. If your validator function takes 2 arguments, mongoose will assume the 2nd argument is a callback.

http://mongoosejs.com/docs/validation.html

**Comment by martijnhiemstra** [comment]
I don't know what I have changed, however it seams to have fixed its self. I do have 2 other issues. 

If I save an object with 2 properties that both are marked as unique and both fields have non unique values (Another object in the database with the 2 same values) then the validation error only contains the first field. Shouldn't it contain both fields that aren't unique?

If I create an index over multiple fields lets say 4 fields, and that index is marked as unique, I receive 4 validation errors. It should only return 1 validation error namely the index being non unique and not 4 messages.

**Comment by matteodelabre** [comment]
Hello @martijnhiemstra, thank you for reporting this. Can you please create a separate issue for each problem you mentioned? This will make things easier to track.
