### ISSUE TITLE
Doesn't work with the new Mongoose 5.x RCs

### ISSUE THREAD

**Issue by devinus** [matteodelabre/mongoose-beautiful-unique-validation#46]
One difference I've already noticed is some errors are returned as `BulkWriteError` and not `MongoError`.

**Comment by johnculviner** [comment]
@matteodelabre can you merge this bad boy?

**Comment by 4doge** [comment]
@johnculviner +1
@matteodelabre do you still support your plugin?

**Comment by matteodelabre** [comment]
Thanks everyone for your patience. I have merged David’s contribution and will publish a new version soon after some tweaking and further testing.

**Comment by johnculviner** [comment]
Thanks for the help (and the library!)
