### ISSUE TITLE
GitHub releases are missing

### ISSUE THREAD

**Issue by galenandrew** [matteodelabre/mongoose-beautiful-unique-validation#8]
Looks like you may have forgotten to push your tags to GitHub after publishing to NPM. Having these tags/releases in GitHub helps developers reference code from exact versions they are using.

Also, it looks like your [repository URL](https://github.com/matteodelabre/mongoose-beautiful-unique-validation/blob/master/package.json#L9) needs updating.

**Comment by matteodelabre** [comment]
Hi, thanks for the report!
I am going to push the tags. :)
