### ISSUE TITLE
Tests failing in the CI

### ISSUE THREAD

**Issue by matteodelabre** [matteodelabre/mongoose-beautiful-unique-validation#9]
The test suite is failing on Travis, but is running as expected locally.
This might be due a discrepancy in the MongoDB setup.

Tests failing are those checking that saving duplicates generates errors.
https://travis-ci.org/matteodelabre/mongoose-beautiful-unique-validation/jobs/104286507

**Comment by matteodelabre** [comment]
Update: currently working with Travis to fix this.

**Comment by Zertz** [comment]
Have you tried updating MongoDB? Travis uses an old version.

Looks like you should be able to [pull a Docker container](https://github.com/travis-ci/travis-ci/issues/3694#issuecomment-155186560) with the version you want.

**Comment by matteodelabre** [comment]
Going to try that, thank you. :)

**Comment by matteodelabre** [comment]
It worked! Thank you so much
